In [1]:
import matplotlib.pyplot as plt
import matplotlib
import argparse 
import joblib
import cv2
import os
import torch 
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import time
import pickle
import random
import pretrainedmodels
import torchvision
import pickle

matplotlib.style.use('ggplot')

from imutils import paths
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from torchvision.transforms import transforms
from torch.utils.data import DataLoader, Dataset
from torchvision import models
# from tqdm import tqdm_notebook as tqdm
from tqdm import tqdm

'''
SEED Everything
'''
def seed_everything(SEED=42):
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)
    # torch.backends.cudnn.deterministic = True
    # os.environ['PYTHONHASHSEED']=str(SEED)
    # torch.backends.cudnn.benchmark = False # as all the inputs are not of same size
SEED=42
seed_everything(SEED=SEED)
'''
SEED Everything
'''

'\nSEED Everything\n'

In [2]:
if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'

epochs = 5

In [3]:
# image_paths = list(paths.list_images('./caltech/101_ObjectCategories'))

In [4]:
# data = []
# labels = []
# label_names = []
# for image_path in image_paths:
#     label = image_path.split(os.path.sep)[-2]
#     if label == 'BACKGROUND_Google':
#         continue

#     image = cv2.imread(image_path)
#     image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

#     data.append(image)
#     label_names.append(label)
#     labels.append(label)
    


In [3]:
file1 = open("./cal_data_input.pkl", 'rb')
data = pickle.load(file1)
file2 = open("./cal_data_label.pkl", 'rb')
labels = pickle.load(file2)

In [4]:
data = np.array(data)
labels = np.array(labels)
# f = open("./cal_data_label.pkl", 'wb')
# pickle.dump(labels, f)

In [5]:
# one hot encode
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
print(len(lb.classes_))
print(labels)

101
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [6]:
(X, x_val , Y, y_val) = train_test_split(data, labels, 
                                                    test_size=0.2,  
                                                    stratify=labels,
                                                    random_state=42)

(x_train, x_test, y_train, y_test) = train_test_split(X, Y, 
                                                    test_size=0.25, 
                                                    random_state=42)

print(f"x_train examples: {x_train.shape}\nx_test examples: {x_test.shape}\nx_val examples: {x_val.shape}")

x_train examples: (5205,)
x_test examples: (1736,)
x_val examples: (1736,)


In [7]:
# define transforms
train_transform = transforms.Compose(
    [transforms.ToPILImage(),
	 transforms.Resize((224, 224)),
    #  transforms.RandomRotation((-30, 30)),
    #  transforms.RandomHorizontalFlip(p=0.5),
    #  transforms.RandomVerticalFlip(p=0.5),
     transforms.ToTensor(),
     transforms.Normalize(mean=[0.485, 0.456, 0.406],
                          std=[0.229, 0.224, 0.225])])
val_transform = transforms.Compose(
    [transforms.ToPILImage(),
	 transforms.Resize((224, 224)),
     transforms.ToTensor(),
     transforms.Normalize(mean=[0.485, 0.456, 0.406],
                          std=[0.229, 0.224, 0.225])])

In [8]:
# custom dataset
class ImageDataset(Dataset):
    def __init__(self, images, labels=None, transforms=None):
        self.X = images
        self.y = labels
        self.transforms = transforms
         
    def __len__(self):
        return (len(self.X))
    
    def __getitem__(self, i):
        data = self.X[i][:]
        
        if self.transforms:
            data = self.transforms(data)
            
        if self.y is not None:
            return (data, self.y[i])
        else:
            return data
 
train_data = ImageDataset(x_train, y_train, train_transform)
val_data = ImageDataset(x_val, y_val, val_transform)
test_data = ImageDataset(x_test, y_test, val_transform)
 
# dataloaders
trainloader = DataLoader(train_data, batch_size=16, shuffle=True,num_workers=16)
valloader = DataLoader(val_data, batch_size=16, shuffle=True,num_workers=16)
testloader = DataLoader(test_data, batch_size=16, shuffle=False,num_workers=16)

In [16]:
class ResNet34(nn.Module):
    def __init__(self, pretrained):
        super(ResNet34, self).__init__()
        if pretrained is True:
            self.model = pretrainedmodels.__dict__['resnet34'](pretrained='imagenet')
        else:
            self.model = pretrainedmodels.__dict__['resnet34'](pretrained=None)
        
        self.l0 = nn.Linear(512, len(lb.classes_))
        self.dropout = nn.Dropout2d(0.4)

    def forward(self, x):
        # get the batch size only, ignore (c, h, w)
        batch, _, _, _ = x.shape
        x = self.model.features(x)
        x = F.adaptive_avg_pool2d(x, 1).reshape(batch, -1)
        x = self.dropout(x)
        l0 = self.l0(x)
        return l0

model = ResNet34(pretrained=False).to(device)
print(model)

# optimizer
optimizer = optim.SGD(model.parameters(), lr=1e-3, momentum=0.9, weight_decay=5e-4)
# loss function
criterion = nn.CrossEntropyLoss()

ResNet34(
  (model): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=

In [ ]:
print(f"Training on {len(train_data)} examples, validating on {len(val_data)} examples")

#validation function
def validate(model, dataloader):
    print('Validating')
    model.eval()
    val_running_loss = 0.0
    val_running_correct = 0
    with torch.no_grad():
        for i, data in tqdm(enumerate(dataloader), total=int(len(val_data)/dataloader.batch_size)):
            data, target = data[0].to(device), data[1].to(device)
            outputs = model(data)
            loss = criterion(outputs, torch.max(target, 1)[1])
            
            val_running_loss += loss.item()
            _, preds = torch.max(outputs.data, 1)
            val_running_correct += (preds == torch.max(target, 1)[1]).sum().item()
        
        val_loss = val_running_loss/len(dataloader.dataset)
        val_accuracy = 100. * val_running_correct/len(dataloader.dataset)
        print(f'Val Loss: {val_loss:.4f}, Val Acc: {val_accuracy:.2f}')
        
        return val_loss, val_accuracy

# training function
def fit(model, dataloader):
    print('Training')
    model.train()
    train_running_loss = 0.0
    train_running_correct = 0
    for i, data in tqdm(enumerate(dataloader), total=int(len(train_data)/dataloader.batch_size)):
        data, target = data[0].to(device), data[1].to(device)
        optimizer.zero_grad()
        outputs = model(data)
        # print(outputs)
        # print(torch.max(target, 1)[1])
        loss = criterion(outputs, torch.max(target, 1)[1])
        train_running_loss += loss.item()
        _, preds = torch.max(outputs.data, 1)
        train_running_correct += (preds == torch.max(target, 1)[1]).sum().item()
        loss.backward()
        optimizer.step()
        
    train_loss = train_running_loss/len(dataloader.dataset)
    train_accuracy = 100. * train_running_correct/len(dataloader.dataset)
    
    print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_accuracy:.2f}")
    
    return train_loss, train_accuracy

epochs = 100
train_loss , train_accuracy = [], []
val_loss , val_accuracy = [], []
start = time.time()
for epoch in range(epochs):
    print(f"Epoch {epoch+1} of {epochs}")
    train_epoch_loss, train_epoch_accuracy = fit(model, trainloader)
    val_epoch_loss, val_epoch_accuracy = validate(model, valloader)
    train_loss.append(train_epoch_loss)
    train_accuracy.append(train_epoch_accuracy)
    val_loss.append(val_epoch_loss)
    val_accuracy.append(val_epoch_accuracy)
end = time.time()

print((end-start)/60, 'minutes')

Training on 5205 examples, validating on 1736 examples
Epoch 1 of 100
Training


326it [00:11, 28.35it/s]                         

Train Loss: 0.2539, Train Acc: 17.04
Validating



109it [00:01, 63.31it/s]                         

Val Loss: 0.2232, Val Acc: 23.56
Epoch 2 of 100
Training



326it [00:11, 27.94it/s]                         

Train Loss: 0.2223, Train Acc: 25.61
Validating



109it [00:01, 63.84it/s]                         

Val Loss: 0.2020, Val Acc: 29.09
Epoch 3 of 100
Training



326it [00:11, 28.54it/s]                         

Train Loss: 0.2016, Train Acc: 30.45
Validating



109it [00:01, 62.41it/s]                         

Val Loss: 0.1883, Val Acc: 35.54
Epoch 4 of 100
Training



326it [00:11, 28.80it/s]                         

Train Loss: 0.1847, Train Acc: 35.29
Validating



109it [00:01, 61.24it/s]                         

Val Loss: 0.1748, Val Acc: 38.48
Epoch 5 of 100
Training



326it [00:11, 28.30it/s]                         


Train Loss: 0.1702, Train Acc: 38.67
Validating


109it [00:01, 58.02it/s]                         

Val Loss: 0.1705, Val Acc: 40.03
Epoch 6 of 100
Training



326it [00:11, 28.69it/s]                         

Train Loss: 0.1574, Train Acc: 42.90
Validating



109it [00:01, 63.20it/s]                         

Val Loss: 0.1565, Val Acc: 44.07
Epoch 7 of 100
Training



326it [00:11, 29.00it/s]                         


Train Loss: 0.1458, Train Acc: 46.17
Validating


109it [00:01, 63.04it/s]                         

Val Loss: 0.1498, Val Acc: 44.93
Epoch 8 of 100
Training



326it [00:11, 28.47it/s]                         

Train Loss: 0.1366, Train Acc: 48.86
Validating



109it [00:01, 62.55it/s]                         

Val Loss: 0.1435, Val Acc: 47.52
Epoch 9 of 100
Training



326it [00:11, 28.35it/s]                         

Train Loss: 0.1256, Train Acc: 51.70
Validating



109it [00:01, 59.42it/s]                         

Val Loss: 0.1382, Val Acc: 50.00
Epoch 10 of 100
Training



326it [00:11, 28.13it/s]                         

Train Loss: 0.1155, Train Acc: 55.10
Validating



109it [00:01, 62.85it/s]                         


Val Loss: 0.1370, Val Acc: 49.94
Epoch 11 of 100
Training


326it [00:11, 28.65it/s]                         

Train Loss: 0.1069, Train Acc: 58.16
Validating



109it [00:01, 57.63it/s]                         

Val Loss: 0.1336, Val Acc: 49.65
Epoch 12 of 100
Training



326it [00:11, 28.69it/s]                         

Train Loss: 0.0974, Train Acc: 60.40
Validating



109it [00:01, 58.79it/s]                         

Val Loss: 0.1205, Val Acc: 55.53
Epoch 13 of 100
Training



326it [00:11, 28.46it/s]                         

Train Loss: 0.0859, Train Acc: 65.46
Validating



109it [00:01, 61.41it/s]                         

Val Loss: 0.1164, Val Acc: 56.62
Epoch 14 of 100
Training



326it [00:11, 28.67it/s]                         

Train Loss: 0.0757, Train Acc: 68.36
Validating



109it [00:01, 61.49it/s]                         

Val Loss: 0.1129, Val Acc: 58.41
Epoch 15 of 100
Training



326it [00:11, 28.70it/s]                         

Train Loss: 0.0674, Train Acc: 71.64
Validating



109it [00:01, 60.78it/s]                         

Val Loss: 0.1121, Val Acc: 57.09
Epoch 16 of 100
Training



326it [00:11, 28.43it/s]                         

Train Loss: 0.0560, Train Acc: 76.39
Validating



109it [00:01, 60.79it/s]                         

Val Loss: 0.1116, Val Acc: 58.58
Epoch 17 of 100
Training



326it [00:11, 27.77it/s]                         

Train Loss: 0.0472, Train Acc: 80.23
Validating



109it [00:01, 62.70it/s]                         

Val Loss: 0.1041, Val Acc: 60.77
Epoch 18 of 100
Training



326it [00:11, 28.77it/s]                         

Train Loss: 0.0372, Train Acc: 84.92
Validating



109it [00:01, 62.66it/s]                         


Val Loss: 0.1323, Val Acc: 54.90
Epoch 19 of 100
Training


326it [00:11, 28.77it/s]                         

Train Loss: 0.0318, Train Acc: 86.88
Validating



109it [00:01, 62.45it/s]                         

Val Loss: 0.1036, Val Acc: 61.29
Epoch 20 of 100
Training



326it [00:11, 28.42it/s]                         

Train Loss: 0.0230, Train Acc: 91.34
Validating



109it [00:01, 61.98it/s]                         

Val Loss: 0.1082, Val Acc: 61.18
Epoch 21 of 100
Training



326it [00:11, 28.64it/s]                         

Train Loss: 0.0174, Train Acc: 93.68
Validating



109it [00:01, 62.50it/s]                         

Val Loss: 0.1123, Val Acc: 61.41
Epoch 22 of 100
Training



326it [00:11, 28.57it/s]                         

Train Loss: 0.0136, Train Acc: 95.60
Validating



109it [00:01, 63.28it/s]                         

Val Loss: 0.1067, Val Acc: 63.36
Epoch 23 of 100
Training



326it [00:11, 28.84it/s]                         

Train Loss: 0.0099, Train Acc: 97.06
Validating



109it [00:01, 63.12it/s]                         


Val Loss: 0.1039, Val Acc: 62.44
Epoch 24 of 100
Training


326it [00:11, 29.14it/s]                         

Train Loss: 0.0094, Train Acc: 96.75
Validating



109it [00:01, 62.58it/s]                         

Val Loss: 0.1044, Val Acc: 63.13
Epoch 25 of 100
Training



326it [00:11, 29.11it/s]                         

Train Loss: 0.0083, Train Acc: 97.23
Validating



109it [00:01, 62.53it/s]                         

Val Loss: 0.1163, Val Acc: 61.35
Epoch 26 of 100
Training



326it [00:11, 28.87it/s]                         

Train Loss: 0.0077, Train Acc: 97.48
Validating



109it [00:01, 62.90it/s]                         

Val Loss: 0.1104, Val Acc: 62.15
Epoch 27 of 100
Training



326it [00:11, 28.81it/s]                         

Train Loss: 0.0068, Train Acc: 97.79
Validating



109it [00:01, 63.21it/s]                         

Val Loss: 0.1086, Val Acc: 63.82
Epoch 28 of 100
Training



326it [00:11, 28.62it/s]                         

Train Loss: 0.0057, Train Acc: 98.50
Validating



109it [00:01, 56.81it/s]                         

Val Loss: 0.1121, Val Acc: 62.04
Epoch 29 of 100
Training



326it [00:11, 28.68it/s]                         

Train Loss: 0.0046, Train Acc: 99.08
Validating



109it [00:01, 63.77it/s]                         


Val Loss: 0.1094, Val Acc: 63.71
Epoch 30 of 100
Training


326it [00:11, 28.62it/s]                         

Train Loss: 0.0044, Train Acc: 98.90
Validating



109it [00:01, 64.56it/s]                         

Val Loss: 0.1053, Val Acc: 63.94
Epoch 31 of 100
Training



326it [00:11, 28.15it/s]                         

Train Loss: 0.0030, Train Acc: 99.33
Validating



109it [00:01, 58.11it/s]                         

Val Loss: 0.1108, Val Acc: 63.13
Epoch 32 of 100
Training



326it [00:11, 28.76it/s]                         

Train Loss: 0.0026, Train Acc: 99.48
Validating



109it [00:01, 63.37it/s]                         

Val Loss: 0.1087, Val Acc: 62.33
Epoch 33 of 100
Training



326it [00:11, 28.67it/s]                         

Train Loss: 0.0022, Train Acc: 99.67
Validating



109it [00:01, 62.02it/s]                         

Val Loss: 0.1037, Val Acc: 64.57
Epoch 34 of 100
Training



326it [00:11, 28.83it/s]                         

Train Loss: 0.0016, Train Acc: 99.81
Validating



109it [00:01, 62.54it/s]                         

Val Loss: 0.1035, Val Acc: 64.40
Epoch 35 of 100
Training



326it [00:11, 28.72it/s]                         

Train Loss: 0.0021, Train Acc: 99.63
Validating



109it [00:01, 61.35it/s]                         

Val Loss: 0.1024, Val Acc: 65.26
Epoch 36 of 100
Training



326it [00:11, 28.37it/s]                         

Train Loss: 0.0022, Train Acc: 99.58
Validating



109it [00:01, 60.10it/s]                         

Val Loss: 0.1058, Val Acc: 64.63
Epoch 37 of 100
Training



326it [00:11, 28.28it/s]                         

Train Loss: 0.0017, Train Acc: 99.75
Validating



109it [00:01, 60.35it/s]                         

Val Loss: 0.1108, Val Acc: 64.98
Epoch 38 of 100
Training



326it [00:11, 28.82it/s]                         

Train Loss: 0.0016, Train Acc: 99.77
Validating



109it [00:01, 60.65it/s]                         

Val Loss: 0.1033, Val Acc: 65.61
Epoch 39 of 100
Training



326it [00:11, 27.63it/s]                         

Train Loss: 0.0014, Train Acc: 99.77
Validating



109it [00:01, 58.67it/s]                         

Val Loss: 0.1088, Val Acc: 64.46
Epoch 40 of 100
Training



326it [00:11, 28.59it/s]                         

Train Loss: 0.0016, Train Acc: 99.71
Validating



109it [00:01, 60.63it/s]                         

Val Loss: 0.1047, Val Acc: 64.23
Epoch 41 of 100
Training



326it [00:11, 27.97it/s]                         

Train Loss: 0.0018, Train Acc: 99.62
Validating



109it [00:01, 61.20it/s]                         

Val Loss: 0.1052, Val Acc: 64.80
Epoch 42 of 100
Training



326it [00:11, 28.56it/s]                         

Train Loss: 0.0013, Train Acc: 99.85
Validating



109it [00:01, 61.58it/s]                         


Val Loss: 0.1063, Val Acc: 65.55
Epoch 43 of 100
Training


326it [00:11, 28.70it/s]                         

Train Loss: 0.0012, Train Acc: 99.90
Validating



109it [00:01, 61.85it/s]                         

Val Loss: 0.1065, Val Acc: 65.32
Epoch 44 of 100
Training



326it [00:11, 28.71it/s]                         

Train Loss: 0.0010, Train Acc: 99.77
Validating



109it [00:01, 60.48it/s]                         

Val Loss: 0.1096, Val Acc: 64.00
Epoch 45 of 100
Training



326it [00:11, 28.62it/s]                         

Train Loss: 0.0011, Train Acc: 99.85
Validating



109it [00:01, 62.27it/s]                         

Val Loss: 0.1029, Val Acc: 64.86
Epoch 46 of 100
Training



326it [00:11, 28.51it/s]                         

Train Loss: 0.0008, Train Acc: 99.87
Validating



109it [00:01, 61.73it/s]                         

Val Loss: 0.1032, Val Acc: 65.67
Epoch 47 of 100
Training



326it [00:11, 28.67it/s]                         

Train Loss: 0.0009, Train Acc: 99.88
Validating



109it [00:01, 60.34it/s]                         

Val Loss: 0.1050, Val Acc: 65.15
Epoch 48 of 100
Training



326it [00:11, 28.55it/s]                         

Train Loss: 0.0008, Train Acc: 99.90
Validating



109it [00:01, 62.10it/s]                         

Val Loss: 0.1023, Val Acc: 65.09
Epoch 49 of 100
Training



326it [00:11, 28.68it/s]                         

Train Loss: 0.0007, Train Acc: 99.94
Validating



109it [00:01, 60.32it/s]                         

Val Loss: 0.0996, Val Acc: 65.96
Epoch 50 of 100
Training



326it [00:11, 28.22it/s]                         


Train Loss: 0.0007, Train Acc: 99.92
Validating


109it [00:01, 60.11it/s]                         

Val Loss: 0.1027, Val Acc: 64.29
Epoch 51 of 100
Training



326it [00:11, 28.74it/s]                         

Train Loss: 0.0013, Train Acc: 99.79
Validating



109it [00:01, 61.20it/s]                         

Val Loss: 0.1128, Val Acc: 63.48
Epoch 52 of 100
Training



326it [00:11, 28.68it/s]                         

Train Loss: 0.0015, Train Acc: 99.83
Validating



109it [00:01, 64.40it/s]                         

Val Loss: 0.1060, Val Acc: 65.15
Epoch 53 of 100
Training



326it [00:11, 28.16it/s]                         

Train Loss: 0.0016, Train Acc: 99.62
Validating



109it [00:01, 60.78it/s]                         

Val Loss: 0.1079, Val Acc: 64.40
Epoch 54 of 100
Training



326it [00:11, 28.69it/s]                         

Train Loss: 0.0009, Train Acc: 99.92
Validating



109it [00:01, 60.19it/s]                         

Val Loss: 0.1064, Val Acc: 65.32
Epoch 55 of 100
Training



326it [00:11, 28.52it/s]                         

Train Loss: 0.0007, Train Acc: 99.92
Validating



109it [00:01, 62.61it/s]                         

Val Loss: 0.1028, Val Acc: 64.63
Epoch 56 of 100
Training



 81%|████████  | 263/325 [00:09<00:02, 29.08it/s]