In [1]:
import matplotlib.pyplot as plt
import matplotlib
import argparse 
import joblib
import cv2
import os
import torch 
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import time
import pickle
import random
import pretrainedmodels
import torchvision
import pickle

matplotlib.style.use('ggplot')

from imutils import paths
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from torchvision.transforms import transforms
from torch.utils.data import DataLoader, Dataset
from torchvision import models
# from tqdm import tqdm_notebook as tqdm
from tqdm import tqdm

'''
SEED Everything
'''
def seed_everything(SEED=42):
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)
    # torch.backends.cudnn.deterministic = True
    # os.environ['PYTHONHASHSEED']=str(SEED)
    # torch.backends.cudnn.benchmark = False # as all the inputs are not of same size
SEED=42
seed_everything(SEED=SEED)
'''
SEED Everything
'''

os.environ['CUDA_VISIBLE_DEVICES'] = "1"

In [2]:
if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'

epochs = 5

In [3]:
# f = open("./cal_data_input.pkl", 'wb')
# pickle.dump(data, f)

# f = open("./cal_data_label.pkl", 'wb')
# pickle.dump(labels, f)

file1 = open("./cal_data_input.pkl", 'rb')
data = pickle.load(file1)
file2 = open("./cal_data_label.pkl", 'rb')
label = pickle.load(file2)

In [4]:
data = np.array(data)
labels = np.array(label)

In [5]:
# one hot encode
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
print(len(lb.classes_))
print(labels)

101
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [6]:
(X, x_val , Y, y_val) = train_test_split(data, labels, 
                                                    test_size=0.2,  
                                                    stratify=labels,
                                                    random_state=42)

(x_train, x_test, y_train, y_test) = train_test_split(X, Y, 
                                                    test_size=0.25, 
                                                    random_state=42)

print(f"x_train examples: {x_train.shape}\nx_test examples: {x_test.shape}\nx_val examples: {x_val.shape}")

x_train examples: (5205,)
x_test examples: (1736,)
x_val examples: (1736,)


In [7]:
# define transforms
train_transform = transforms.Compose(
    [transforms.ToPILImage(),
	 transforms.Resize((224, 224)),
    #  transforms.RandomRotation((-30, 30)),
    #  transforms.RandomHorizontalFlip(p=0.5),
    #  transforms.RandomVerticalFlip(p=0.5),
     transforms.ToTensor(),
     transforms.Normalize(mean=[0.485, 0.456, 0.406],
                          std=[0.229, 0.224, 0.225])])
val_transform = transforms.Compose(
    [transforms.ToPILImage(),
	 transforms.Resize((224, 224)),
     transforms.ToTensor(),
     transforms.Normalize(mean=[0.485, 0.456, 0.406],
                          std=[0.229, 0.224, 0.225])])

In [8]:
# custom dataset
class ImageDataset(Dataset):
    def __init__(self, images, labels=None, transforms=None):
        self.X = images
        self.y = labels
        self.transforms = transforms
         
    def __len__(self):
        return (len(self.X))
    
    def __getitem__(self, i):
        data = self.X[i][:]
        
        if self.transforms:
            data = self.transforms(data)
            
        if self.y is not None:
            return (data, self.y[i])
        else:
            return data
 
train_data = ImageDataset(x_train, y_train, train_transform)
val_data = ImageDataset(x_val, y_val, val_transform)
test_data = ImageDataset(x_test, y_test, val_transform)
 
# dataloaders
trainloader = DataLoader(train_data, batch_size=16, shuffle=True,num_workers=16)
valloader = DataLoader(val_data, batch_size=16, shuffle=True,num_workers=16)
testloader = DataLoader(test_data, batch_size=16, shuffle=False,num_workers=16)

In [17]:
class ResNet34(nn.Module):
    def __init__(self, pretrained):
        super(ResNet34, self).__init__()
        if pretrained is True:
            self.model = pretrainedmodels.__dict__['resnet18'](pretrained='imagenet')
        else:
            self.model = pretrainedmodels.__dict__['resnet18'](pretrained=None)
        
        self.l0 = nn.Linear(512, len(lb.classes_))
        self.dropout = nn.Dropout2d(0.4)

    def forward(self, x):
        # get the batch size only, ignore (c, h, w)
        batch, _, _, _ = x.shape
        x = self.model.features(x)
        x = F.adaptive_avg_pool2d(x, 1).reshape(batch, -1)
        x = self.dropout(x)
        l0 = self.l0(x)
        return l0

model = ResNet34(pretrained=False).cuda()
print(model)

# optimizer
optimizer = optim.Adam(model.parameters(), lr=1e-2,)
# loss function
criterion = nn.CrossEntropyLoss()

ResNet34(
  (model): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=

In [ ]:
print(f"Training on {len(train_data)} examples, validating on {len(val_data)} examples")

#validation function
def validate(model, dataloader):
    print('Validating')
    model.eval()
    val_running_loss = 0.0
    val_running_correct = 0
    with torch.no_grad():
        for i, data in tqdm(enumerate(dataloader), total=int(len(val_data)/dataloader.batch_size)):
            data, target = data[0].to(device), data[1].to(device)
            outputs = model(data)
            loss = criterion(outputs, torch.max(target, 1)[1])
            
            val_running_loss += loss.item()
            _, preds = torch.max(outputs.data, 1)
            val_running_correct += (preds == torch.max(target, 1)[1]).sum().item()
        
        val_loss = val_running_loss/len(dataloader.dataset)
        val_accuracy = 100. * val_running_correct/len(dataloader.dataset)
        print(f'Val Loss: {val_loss:.4f}, Val Acc: {val_accuracy:.2f}')
        
        return val_loss, val_accuracy

# training function
def fit(model, dataloader):
    print('Training')
    model.train()
    train_running_loss = 0.0
    train_running_correct = 0
    for i, data in tqdm(enumerate(dataloader), total=int(len(train_data)/dataloader.batch_size)):
        data, target = data[0].cuda(), data[1].cuda()
        optimizer.zero_grad()
        outputs = model(data)
        # print(outputs)
        # print(torch.max(target, 1)[1])
        loss = criterion(outputs, torch.max(target, 1)[1])
        train_running_loss += loss.item()
        _, preds = torch.max(outputs.data, 1)
        train_running_correct += (preds == torch.max(target, 1)[1]).sum().item()
        loss.backward()
        optimizer.step()
        
    train_loss = train_running_loss/len(dataloader.dataset)
    train_accuracy = 100. * train_running_correct/len(dataloader.dataset)
    
    print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_accuracy:.2f}")
    
    return train_loss, train_accuracy

epochs = 100
train_loss , train_accuracy = [], []
val_loss , val_accuracy = [], []
start = time.time()
for epoch in range(epochs):
    print(f"Epoch {epoch+1} of {epochs}")
    train_epoch_loss, train_epoch_accuracy = fit(model, trainloader)
    val_epoch_loss, val_epoch_accuracy = validate(model, valloader)
    train_loss.append(train_epoch_loss)
    train_accuracy.append(train_epoch_accuracy)
    val_loss.append(val_epoch_loss)
    val_accuracy.append(val_epoch_accuracy)
end = time.time()

print((end-start)/60, 'minutes')

Training on 5205 examples, validating on 1736 examples
Epoch 1 of 100
Training


326it [00:07, 41.81it/s]                         

Train Loss: 0.2656, Train Acc: 16.41
Validating



109it [00:01, 75.36it/s]                         

Val Loss: 0.2373, Val Acc: 21.83
Epoch 2 of 100
Training



326it [00:07, 41.70it/s]                         

Train Loss: 0.2312, Train Acc: 22.32
Validating



109it [00:01, 75.51it/s]                         

Val Loss: 0.2206, Val Acc: 22.64
Epoch 3 of 100
Training



326it [00:07, 41.25it/s]                         

Train Loss: 0.2129, Train Acc: 26.09
Validating



109it [00:01, 83.11it/s]                        

Val Loss: 0.2198, Val Acc: 25.75
Epoch 4 of 100
Training



326it [00:07, 41.70it/s]                         

Train Loss: 0.2004, Train Acc: 30.89
Validating



109it [00:01, 82.01it/s]                         

Val Loss: 0.1862, Val Acc: 35.37
Epoch 5 of 100
Training



326it [00:07, 42.08it/s]                         

Train Loss: 0.1823, Train Acc: 36.23
Validating



109it [00:01, 82.83it/s]                         

Val Loss: 0.1672, Val Acc: 39.86
Epoch 6 of 100
Training



326it [00:07, 41.27it/s]                         

Train Loss: 0.1638, Train Acc: 41.19
Validating



109it [00:01, 82.67it/s]                        

Val Loss: 0.1541, Val Acc: 44.18
Epoch 7 of 100
Training



326it [00:07, 40.81it/s]                         

Train Loss: 0.1475, Train Acc: 45.98
Validating



109it [00:01, 83.38it/s]                        

Val Loss: 0.1407, Val Acc: 47.47
Epoch 8 of 100
Training



326it [00:07, 41.12it/s]                         

Train Loss: 0.1331, Train Acc: 50.07
Validating



109it [00:01, 82.29it/s]                         

Val Loss: 0.1331, Val Acc: 50.75
Epoch 9 of 100
Training



326it [00:07, 41.02it/s]                         

Train Loss: 0.1202, Train Acc: 53.70
Validating



109it [00:01, 84.06it/s]                         

Val Loss: 0.1195, Val Acc: 55.30
Epoch 10 of 100
Training



326it [00:07, 42.24it/s]                         

Train Loss: 0.1049, Train Acc: 58.12
Validating



109it [00:01, 78.48it/s]                         


Val Loss: 0.1205, Val Acc: 56.34
Epoch 11 of 100
Training


326it [00:07, 41.65it/s]                         

Train Loss: 0.0908, Train Acc: 62.86
Validating



109it [00:01, 75.30it/s]                         

Val Loss: 0.1109, Val Acc: 58.24
Epoch 12 of 100
Training



326it [00:07, 42.34it/s]                         

Train Loss: 0.0777, Train Acc: 67.36
Validating



109it [00:01, 74.05it/s]                         

Val Loss: 0.1047, Val Acc: 61.29
Epoch 13 of 100
Training



326it [00:08, 40.18it/s]                         

Train Loss: 0.0662, Train Acc: 71.83
Validating



109it [00:01, 82.31it/s]                         

Val Loss: 0.0969, Val Acc: 63.02
Epoch 14 of 100
Training



326it [00:08, 40.68it/s]                         

Train Loss: 0.0531, Train Acc: 76.71
Validating



109it [00:01, 83.20it/s]                         

Val Loss: 0.1129, Val Acc: 61.69
Epoch 15 of 100
Training



326it [00:07, 41.89it/s]                         

Train Loss: 0.0426, Train Acc: 80.71
Validating



109it [00:01, 82.34it/s]                         

Val Loss: 0.0996, Val Acc: 64.92
Epoch 16 of 100
Training



326it [00:07, 41.93it/s]                         


Train Loss: 0.0320, Train Acc: 85.69
Validating


109it [00:01, 76.86it/s]                         

Val Loss: 0.1020, Val Acc: 64.92
Epoch 17 of 100
Training



326it [00:07, 41.53it/s]                         

Train Loss: 0.0251, Train Acc: 88.63
Validating



109it [00:01, 81.58it/s]                         

Val Loss: 0.1132, Val Acc: 63.77
Epoch 18 of 100
Training



326it [00:07, 40.85it/s]                         

Train Loss: 0.0208, Train Acc: 90.66
Validating



109it [00:01, 80.77it/s]                        

Val Loss: 0.1072, Val Acc: 65.61
Epoch 19 of 100
Training



326it [00:08, 39.95it/s]                         

Train Loss: 0.0155, Train Acc: 92.51
Validating



109it [00:01, 69.60it/s]                         

Val Loss: 0.1189, Val Acc: 63.77
Epoch 20 of 100
Training



326it [00:08, 38.91it/s]                         

Train Loss: 0.0124, Train Acc: 94.20
Validating



109it [00:01, 82.15it/s]                         

Val Loss: 0.1125, Val Acc: 66.42
Epoch 21 of 100
Training



326it [00:07, 42.08it/s]                         

Train Loss: 0.0121, Train Acc: 94.22
Validating



109it [00:01, 83.69it/s]                         

Val Loss: 0.1108, Val Acc: 67.22
Epoch 22 of 100
Training



326it [00:08, 40.54it/s]                         

Train Loss: 0.0110, Train Acc: 94.52
Validating



109it [00:01, 72.61it/s]                         

Val Loss: 0.1140, Val Acc: 65.84
Epoch 23 of 100
Training



326it [00:07, 41.62it/s]                         

Train Loss: 0.0103, Train Acc: 95.14
Validating



109it [00:01, 82.52it/s]                         

Val Loss: 0.1129, Val Acc: 65.84
Epoch 24 of 100
Training



326it [00:07, 41.93it/s]                         

Train Loss: 0.0091, Train Acc: 95.29
Validating



109it [00:01, 83.84it/s]                         

Val Loss: 0.1174, Val Acc: 67.22
Epoch 25 of 100
Training



326it [00:07, 42.75it/s]                         

Train Loss: 0.0095, Train Acc: 95.27
Validating



109it [00:01, 82.85it/s]                         

Val Loss: 0.1179, Val Acc: 65.84
Epoch 26 of 100
Training



326it [00:07, 42.30it/s]                         

Train Loss: 0.0066, Train Acc: 96.79
Validating



109it [00:01, 80.82it/s]                         

Val Loss: 0.1349, Val Acc: 64.86
Epoch 27 of 100
Training



326it [00:07, 42.07it/s]                         

Train Loss: 0.0070, Train Acc: 96.62
Validating



109it [00:01, 84.00it/s]                         

Val Loss: 0.1286, Val Acc: 64.46
Epoch 28 of 100
Training



326it [00:07, 41.49it/s]                         

Train Loss: 0.0082, Train Acc: 96.12
Validating



109it [00:01, 83.23it/s]                         

Val Loss: 0.1176, Val Acc: 67.22
Epoch 29 of 100
Training



326it [00:07, 41.92it/s]                         

Train Loss: 0.0091, Train Acc: 95.62
Validating



109it [00:01, 77.35it/s]                         

Val Loss: 0.1320, Val Acc: 65.78
Epoch 30 of 100
Training



326it [00:07, 42.04it/s]                         

Train Loss: 0.0080, Train Acc: 96.31
Validating



109it [00:01, 82.35it/s]                         

Val Loss: 0.1263, Val Acc: 67.34
Epoch 31 of 100
Training



326it [00:07, 41.27it/s]                         

Train Loss: 0.0040, Train Acc: 98.12
Validating



109it [00:01, 82.43it/s]                         

Val Loss: 0.1190, Val Acc: 67.86
Epoch 32 of 100
Training



326it [00:07, 41.90it/s]                         

Train Loss: 0.0038, Train Acc: 98.29
Validating



109it [00:01, 84.89it/s]                         

Val Loss: 0.1215, Val Acc: 68.66
Epoch 33 of 100
Training



326it [00:07, 42.51it/s]                         

Train Loss: 0.0065, Train Acc: 96.93
Validating



109it [00:01, 75.85it/s]                         

Val Loss: 0.1447, Val Acc: 64.57
Epoch 34 of 100
Training



326it [00:07, 42.40it/s]                         

Train Loss: 0.0075, Train Acc: 96.71
Validating



109it [00:01, 80.32it/s]                         

Val Loss: 0.1557, Val Acc: 63.36
Epoch 35 of 100
Training



326it [00:07, 41.52it/s]                         

Train Loss: 0.0063, Train Acc: 97.04
Validating



109it [00:01, 81.10it/s]                         

Val Loss: 0.1333, Val Acc: 66.59
Epoch 36 of 100
Training



326it [00:07, 41.82it/s]                         

Train Loss: 0.0080, Train Acc: 96.16
Validating



109it [00:01, 77.69it/s]                         

Val Loss: 0.1393, Val Acc: 65.32
Epoch 37 of 100
Training



326it [00:07, 41.55it/s]                         

Train Loss: 0.0033, Train Acc: 98.41
Validating



109it [00:01, 77.50it/s]                         

Val Loss: 0.1170, Val Acc: 69.01
Epoch 38 of 100
Training



326it [00:07, 40.84it/s]                         

Train Loss: 0.0063, Train Acc: 97.14
Validating



109it [00:01, 83.06it/s]                         

Val Loss: 0.1431, Val Acc: 65.26
Epoch 39 of 100
Training



326it [00:07, 41.46it/s]                         

Train Loss: 0.0038, Train Acc: 98.31
Validating



109it [00:01, 82.40it/s]                         

Val Loss: 0.1357, Val Acc: 67.91
Epoch 40 of 100
Training



326it [00:07, 42.56it/s]                         

Train Loss: 0.0038, Train Acc: 98.19
Validating



109it [00:01, 77.97it/s]                         

Val Loss: 0.1394, Val Acc: 66.71
Epoch 41 of 100
Training



326it [00:07, 42.23it/s]                         

Train Loss: 0.0058, Train Acc: 97.25
Validating



109it [00:01, 83.40it/s]                        

Val Loss: 0.1488, Val Acc: 64.63
Epoch 42 of 100
Training



326it [00:07, 41.46it/s]                         

Train Loss: 0.0044, Train Acc: 97.98
Validating



109it [00:01, 79.52it/s]                         

Val Loss: 0.1625, Val Acc: 65.21
Epoch 43 of 100
Training



326it [00:07, 41.10it/s]                         

Train Loss: 0.0041, Train Acc: 98.14
Validating



109it [00:01, 79.09it/s]                         

Val Loss: 0.1314, Val Acc: 67.51
Epoch 44 of 100
Training



326it [00:07, 41.26it/s]                         

Train Loss: 0.0027, Train Acc: 98.77
Validating



109it [00:01, 82.65it/s]                         

Val Loss: 0.1692, Val Acc: 63.71
Epoch 45 of 100
Training



326it [00:07, 41.21it/s]                         

Train Loss: 0.0091, Train Acc: 95.85
Validating



109it [00:01, 82.17it/s]                         

Val Loss: 0.1574, Val Acc: 64.80
Epoch 46 of 100
Training



326it [00:07, 42.21it/s]                         

Train Loss: 0.0048, Train Acc: 97.75
Validating



109it [00:01, 82.64it/s]                         

Val Loss: 0.1210, Val Acc: 68.61
Epoch 47 of 100
Training



326it [00:07, 42.66it/s]                         

Train Loss: 0.0027, Train Acc: 98.83
Validating



109it [00:01, 73.82it/s]                         

Val Loss: 0.1414, Val Acc: 67.57
Epoch 48 of 100
Training



326it [00:07, 42.49it/s]                         

Train Loss: 0.0035, Train Acc: 98.50
Validating



109it [00:01, 81.11it/s]                         

Val Loss: 0.1476, Val Acc: 65.15
Epoch 49 of 100
Training



326it [00:07, 40.83it/s]                         

Train Loss: 0.0049, Train Acc: 97.58
Validating



109it [00:01, 76.77it/s]                         

Val Loss: 0.1563, Val Acc: 66.24
Epoch 50 of 100
Training



326it [00:07, 41.47it/s]                         

Train Loss: 0.0041, Train Acc: 97.83
Validating



109it [00:01, 79.27it/s]                         

Val Loss: 0.1582, Val Acc: 65.84
Epoch 51 of 100
Training



326it [00:07, 41.63it/s]                         

Train Loss: 0.0025, Train Acc: 98.73
Validating



109it [00:01, 82.26it/s]                         

Val Loss: 0.1495, Val Acc: 67.17
Epoch 52 of 100
Training



326it [00:07, 40.87it/s]                         


Train Loss: 0.0048, Train Acc: 97.64
Validating


109it [00:01, 82.64it/s]                         

Val Loss: 0.1682, Val Acc: 62.67
Epoch 53 of 100
Training



326it [00:07, 42.31it/s]                         

Train Loss: 0.0048, Train Acc: 97.91
Validating



109it [00:01, 83.56it/s]                         

Val Loss: 0.1440, Val Acc: 65.84
Epoch 54 of 100
Training



326it [00:07, 41.76it/s]                         

Train Loss: 0.0044, Train Acc: 98.02
Validating



109it [00:01, 80.28it/s]                         

Val Loss: 0.1528, Val Acc: 66.36
Epoch 55 of 100
Training



326it [00:07, 42.06it/s]                         

Train Loss: 0.0040, Train Acc: 98.27
Validating



109it [00:01, 84.77it/s]                         

Val Loss: 0.1463, Val Acc: 66.94
Epoch 56 of 100
Training



326it [00:07, 41.27it/s]                         

Train Loss: 0.0032, Train Acc: 98.35
Validating



109it [00:01, 79.73it/s]                         


Val Loss: 0.1500, Val Acc: 67.45
Epoch 57 of 100
Training


326it [00:07, 41.82it/s]                         

Train Loss: 0.0035, Train Acc: 98.33
Validating



109it [00:01, 76.60it/s]                         

Val Loss: 0.1634, Val Acc: 64.98
Epoch 58 of 100
Training



326it [00:07, 42.33it/s]                         

Train Loss: 0.0048, Train Acc: 98.00
Validating



109it [00:01, 82.15it/s]                         

Val Loss: 0.1662, Val Acc: 65.38
Epoch 59 of 100
Training



326it [00:07, 42.06it/s]                         

Train Loss: 0.0045, Train Acc: 97.93
Validating



109it [00:01, 80.91it/s]                         

Val Loss: 0.1508, Val Acc: 68.55
Epoch 60 of 100
Training



326it [00:07, 42.12it/s]                         

Train Loss: 0.0046, Train Acc: 97.89
Validating



109it [00:01, 78.67it/s]                        

Val Loss: 0.1535, Val Acc: 66.36
Epoch 61 of 100
Training



326it [00:07, 40.86it/s]                         

Train Loss: 0.0025, Train Acc: 98.96
Validating



109it [00:01, 81.52it/s]                         

Val Loss: 0.1512, Val Acc: 67.97
Epoch 62 of 100
Training



326it [00:07, 42.16it/s]                         

Train Loss: 0.0015, Train Acc: 99.23
Validating



109it [00:01, 83.93it/s]                         

Val Loss: 0.1507, Val Acc: 68.61
Epoch 63 of 100
Training



326it [00:08, 37.25it/s]                         

Train Loss: 0.0019, Train Acc: 98.92
Validating



109it [00:01, 84.22it/s]                         

Val Loss: 0.1744, Val Acc: 65.55
Epoch 64 of 100
Training



326it [00:07, 42.21it/s]                         

Train Loss: 0.0042, Train Acc: 98.12
Validating



109it [00:01, 78.41it/s]                         

Val Loss: 0.1993, Val Acc: 64.46
Epoch 65 of 100
Training



326it [00:07, 42.87it/s]                         

Train Loss: 0.0070, Train Acc: 96.95
Validating



109it [00:01, 79.03it/s]                         

Val Loss: 0.1606, Val Acc: 66.24
Epoch 66 of 100
Training



326it [00:07, 41.69it/s]                         

Train Loss: 0.0034, Train Acc: 98.60
Validating



109it [00:01, 83.61it/s]                         

Val Loss: 0.1509, Val Acc: 68.15
Epoch 67 of 100
Training



326it [00:07, 41.50it/s]                         

Train Loss: 0.0023, Train Acc: 98.73
Validating



109it [00:01, 79.61it/s]                         

Val Loss: 0.1573, Val Acc: 67.40
Epoch 68 of 100
Training



326it [00:07, 41.99it/s]                         

Train Loss: 0.0035, Train Acc: 98.44
Validating



109it [00:01, 80.73it/s]                         

Val Loss: 0.1493, Val Acc: 69.24
Epoch 69 of 100
Training



326it [00:08, 40.44it/s]                         

Train Loss: 0.0020, Train Acc: 98.98
Validating



109it [00:01, 83.68it/s]                         

Val Loss: 0.1456, Val Acc: 68.03
Epoch 70 of 100
Training



326it [00:07, 42.06it/s]                         

Train Loss: 0.0029, Train Acc: 98.66
Validating



109it [00:01, 82.73it/s]                         

Val Loss: 0.1440, Val Acc: 68.43
Epoch 71 of 100
Training



326it [00:07, 41.41it/s]                         

Train Loss: 0.0029, Train Acc: 98.66
Validating



109it [00:01, 80.00it/s]                         

Val Loss: 0.1532, Val Acc: 66.30
Epoch 72 of 100
Training



326it [00:07, 42.07it/s]                         

Train Loss: 0.0015, Train Acc: 99.12
Validating



109it [00:01, 78.71it/s]                         

Val Loss: 0.1527, Val Acc: 68.38
Epoch 73 of 100
Training



326it [00:07, 41.98it/s]                         

Train Loss: 0.0032, Train Acc: 98.67
Validating



109it [00:01, 79.12it/s]                         


Val Loss: 0.1708, Val Acc: 66.65
Epoch 74 of 100
Training


326it [00:08, 40.74it/s]                         

Train Loss: 0.0047, Train Acc: 98.16
Validating



109it [00:01, 75.05it/s]                         

Val Loss: 0.1607, Val Acc: 67.11
Epoch 75 of 100
Training



326it [00:07, 41.33it/s]                         

Train Loss: 0.0056, Train Acc: 97.81
Validating



109it [00:01, 78.63it/s]                        

Val Loss: 0.1874, Val Acc: 64.69
Epoch 76 of 100
Training



326it [00:07, 42.38it/s]                         

Train Loss: 0.0044, Train Acc: 98.31
Validating



109it [00:01, 80.95it/s]                         

Val Loss: 0.1570, Val Acc: 69.18
Epoch 77 of 100
Training



326it [00:07, 42.06it/s]                         

Train Loss: 0.0026, Train Acc: 98.85
Validating



109it [00:01, 77.38it/s]                         

Val Loss: 0.1461, Val Acc: 68.49
Epoch 78 of 100
Training



326it [00:07, 40.92it/s]                         

Train Loss: 0.0029, Train Acc: 98.62
Validating



109it [00:01, 83.52it/s]                         

Val Loss: 0.1494, Val Acc: 69.35
Epoch 79 of 100
Training



326it [00:08, 40.15it/s]                         

Train Loss: 0.0025, Train Acc: 98.89
Validating



109it [00:01, 81.09it/s]                         

Val Loss: 0.1779, Val Acc: 68.26
Epoch 80 of 100
Training



326it [00:07, 42.07it/s]                         

Train Loss: 0.0038, Train Acc: 98.52
Validating



109it [00:01, 81.00it/s]                         

Val Loss: 0.1534, Val Acc: 68.09
Epoch 81 of 100
Training



326it [00:07, 41.08it/s]                         

Train Loss: 0.0018, Train Acc: 99.17
Validating



109it [00:01, 83.63it/s]                         

Val Loss: 0.1750, Val Acc: 66.42
Epoch 82 of 100
Training



326it [00:07, 40.82it/s]                         

Train Loss: 0.0020, Train Acc: 99.23
Validating



109it [00:01, 78.62it/s]                         

Val Loss: 0.1716, Val Acc: 67.91
Epoch 83 of 100
Training



326it [00:07, 42.01it/s]                         

Train Loss: 0.0024, Train Acc: 99.08
Validating



109it [00:01, 80.38it/s]                         

Val Loss: 0.1995, Val Acc: 64.92
Epoch 84 of 100
Training



326it [00:07, 41.15it/s]                         

Train Loss: 0.0037, Train Acc: 98.44
Validating



109it [00:01, 82.82it/s]                         

Val Loss: 0.1514, Val Acc: 67.68
Epoch 85 of 100
Training



326it [00:07, 41.70it/s]                         

Train Loss: 0.0036, Train Acc: 98.54
Validating



109it [00:01, 82.78it/s]                         

Val Loss: 0.1767, Val Acc: 66.42
Epoch 86 of 100
Training



326it [00:07, 41.56it/s]                         

Train Loss: 0.0034, Train Acc: 98.48
Validating



109it [00:01, 81.44it/s]                         

Val Loss: 0.1634, Val Acc: 67.34
Epoch 87 of 100
Training



326it [00:07, 43.29it/s]                         

Train Loss: 0.0021, Train Acc: 99.02
Validating



109it [00:01, 81.69it/s]                         

Val Loss: 0.1808, Val Acc: 68.09
Epoch 88 of 100
Training



326it [00:07, 42.08it/s]                         

Train Loss: 0.0028, Train Acc: 98.67
Validating



109it [00:01, 79.29it/s]                         

Val Loss: 0.1623, Val Acc: 68.84
Epoch 89 of 100
Training



326it [00:08, 40.70it/s]                         

Train Loss: 0.0013, Train Acc: 99.40
Validating



109it [00:01, 79.57it/s]                         

Val Loss: 0.1898, Val Acc: 65.26
Epoch 90 of 100
Training



326it [00:07, 42.07it/s]                         

Train Loss: 0.0046, Train Acc: 97.96
Validating



109it [00:01, 83.04it/s]                         

Val Loss: 0.1801, Val Acc: 67.74
Epoch 91 of 100
Training



326it [00:07, 41.08it/s]                         

Train Loss: 0.0048, Train Acc: 98.29
Validating



109it [00:01, 79.92it/s]                         


Val Loss: 0.1895, Val Acc: 64.57
Epoch 92 of 100
Training


326it [00:08, 40.10it/s]                         

Train Loss: 0.0032, Train Acc: 98.56
Validating



109it [00:01, 76.50it/s]                         

Val Loss: 0.1574, Val Acc: 68.89
Epoch 93 of 100
Training



326it [00:07, 42.35it/s]                         

Train Loss: 0.0023, Train Acc: 98.92
Validating



109it [00:01, 75.39it/s]                         

Val Loss: 0.1512, Val Acc: 68.26
Epoch 94 of 100
Training



326it [00:07, 41.75it/s]                         

Train Loss: 0.0022, Train Acc: 99.06
Validating



109it [00:01, 84.20it/s]                         

Val Loss: 0.1596, Val Acc: 68.26
Epoch 95 of 100
Training



326it [00:07, 42.24it/s]                         

Train Loss: 0.0021, Train Acc: 99.29
Validating



109it [00:01, 83.68it/s]                         

Val Loss: 0.1643, Val Acc: 68.03
Epoch 96 of 100
Training



 70%|██████▉   | 226/325 [00:05<00:02, 42.57it/s]